# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0c6170f6-a5c5-4ccd-84c3-3ac9487a26f4";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-0c6170f6-a5c5-4ccd-84c3-3ac9487a26f4".device = "/dev/disk/by-uuid/0c6170f6-a5c5-4ccd-84c3-3ac9487a26f4";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-0c6170f6-a5c5-4ccd-84c3-3ac9487a26f4";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-0c6170f6-a5c5-4ccd-84c3-3ac9487a26f4";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E710-27BC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
